# Generated by Django 3.1 on 2020-09-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demo',
            new_name='Test',
        ),
    ]
