kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv1
  resources:
    requests:
      storage: 1Gi
